// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {services} from '../models';
import {version} from '../models';

export function AskAI(arg1:string):Promise<Record<string, any>>;

export function ClearAlerts():Promise<void>;

export function ClearAllInsights():Promise<void>;

export function ClearChatSession(arg1:string):Promise<void>;

export function ClearOldInsights():Promise<void>;

export function CreateChatSession(arg1:string):Promise<models.ChatSession>;

export function DeleteChatSession(arg1:string):Promise<void>;

export function DismissAlert(arg1:string):Promise<void>;

export function ExplainConnection(arg1:string,arg2:number):Promise<Record<string, any>>;

export function ExplainNetworkActivity():Promise<Record<string, any>>;

export function ExplainPort(arg1:number,arg2:string):Promise<Record<string, any>>;

export function ExplainProcess(arg1:number):Promise<Record<string, any>>;

export function ExportChatSession(arg1:string,arg2:string):Promise<Record<string, any>>;

export function GetAIConfig():Promise<models.AIConfig>;

export function GetAlertConfig():Promise<models.AlertConfig>;

export function GetAlerts():Promise<Array<models.Alert>>;

export function GetAllChatSessions():Promise<Array<models.ChatSessionSummary>>;

export function GetAutoInsights(arg1:boolean):Promise<Array<models.AutoInsight>>;

export function GetAvailableProviders():Promise<Array<services.ProviderInfo>>;

export function GetChatSession(arg1:string):Promise<models.ChatSession>;

export function GetDetailedStats():Promise<models.SystemStats>;

export function GetDevEnvironmentInfo():Promise<models.DevEnvironmentInfo>;

export function GetNetworkUsage():Promise<Array<models.NetworkUsage>>;

export function GetPorts():Promise<Array<models.PortInfo>>;

export function GetPrivacyConfig():Promise<models.PrivacyConfig>;

export function GetProcesses():Promise<Array<models.ProcessInfo>>;

export function GetPromptTemplates():Promise<Array<models.PromptTemplate>>;

export function GetQuickStats():Promise<Record<string, any>>;

export function GetResourceTimeline(arg1:number):Promise<Array<models.ResourceTimelinePoint>>;

export function GetSecurityInfo():Promise<models.SecurityInfo>;

export function GetSecurityInfoWithGeo():Promise<models.SecurityInfo>;

export function GetShortVersion():Promise<string>;

export function GetSystemContext():Promise<models.SystemContext>;

export function GetSystemStats():Promise<Record<string, number>>;

export function GetTimeMachine(arg1:number):Promise<models.TimeMachineView>;

export function GetVersion():Promise<version.Info>;

export function GetVersionString():Promise<string>;

export function IsAIConfigured():Promise<boolean>;

export function KillProcess(arg1:number):Promise<Record<string, any>>;

export function MarkInsightAsRead(arg1:string):Promise<void>;

export function MinimizeToTray():Promise<void>;

export function QuitApp():Promise<void>;

export function RemoveContainer(arg1:string):Promise<void>;

export function RestartContainer(arg1:string):Promise<void>;

export function SendChatMessage(arg1:string,arg2:string):Promise<Record<string, any>>;

export function SendChatMessageStreaming(arg1:string,arg2:string):Promise<Record<string, any>>;

export function SendTestNotification(arg1:string,arg2:string):Promise<void>;

export function SetAIConfig(arg1:models.AIConfig):Promise<void>;

export function SetAlertConfig(arg1:models.AlertConfig):Promise<void>;

export function SetPrivacyConfig(arg1:models.PrivacyConfig):Promise<Record<string, any>>;

export function SetProcessPriority(arg1:number,arg2:number):Promise<Record<string, any>>;

export function ShowFromTray():Promise<void>;

export function StartContainer(arg1:string):Promise<void>;

export function StopContainer(arg1:string):Promise<void>;

export function UpdateChatSessionTitle(arg1:string,arg2:string):Promise<void>;
