// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AskAI(arg1) {
  return window['go']['main']['App']['AskAI'](arg1);
}

export function ClearAlerts() {
  return window['go']['main']['App']['ClearAlerts']();
}

export function ClearAllInsights() {
  return window['go']['main']['App']['ClearAllInsights']();
}

export function ClearChatSession(arg1) {
  return window['go']['main']['App']['ClearChatSession'](arg1);
}

export function ClearOldInsights() {
  return window['go']['main']['App']['ClearOldInsights']();
}

export function CreateChatSession(arg1) {
  return window['go']['main']['App']['CreateChatSession'](arg1);
}

export function DeleteChatSession(arg1) {
  return window['go']['main']['App']['DeleteChatSession'](arg1);
}

export function DismissAlert(arg1) {
  return window['go']['main']['App']['DismissAlert'](arg1);
}

export function ExplainConnection(arg1, arg2) {
  return window['go']['main']['App']['ExplainConnection'](arg1, arg2);
}

export function ExplainNetworkActivity() {
  return window['go']['main']['App']['ExplainNetworkActivity']();
}

export function ExplainPort(arg1, arg2) {
  return window['go']['main']['App']['ExplainPort'](arg1, arg2);
}

export function ExplainProcess(arg1) {
  return window['go']['main']['App']['ExplainProcess'](arg1);
}

export function ExportChatSession(arg1, arg2) {
  return window['go']['main']['App']['ExportChatSession'](arg1, arg2);
}

export function GetAIConfig() {
  return window['go']['main']['App']['GetAIConfig']();
}

export function GetAlertConfig() {
  return window['go']['main']['App']['GetAlertConfig']();
}

export function GetAlerts() {
  return window['go']['main']['App']['GetAlerts']();
}

export function GetAllChatSessions() {
  return window['go']['main']['App']['GetAllChatSessions']();
}

export function GetAutoInsights(arg1) {
  return window['go']['main']['App']['GetAutoInsights'](arg1);
}

export function GetAvailableProviders() {
  return window['go']['main']['App']['GetAvailableProviders']();
}

export function GetChatSession(arg1) {
  return window['go']['main']['App']['GetChatSession'](arg1);
}

export function GetDetailedStats() {
  return window['go']['main']['App']['GetDetailedStats']();
}

export function GetDevEnvironmentInfo() {
  return window['go']['main']['App']['GetDevEnvironmentInfo']();
}

export function GetNetworkUsage() {
  return window['go']['main']['App']['GetNetworkUsage']();
}

export function GetPorts() {
  return window['go']['main']['App']['GetPorts']();
}

export function GetProcesses() {
  return window['go']['main']['App']['GetProcesses']();
}

export function GetPromptTemplates() {
  return window['go']['main']['App']['GetPromptTemplates']();
}

export function GetQuickStats() {
  return window['go']['main']['App']['GetQuickStats']();
}

export function GetResourceTimeline(arg1) {
  return window['go']['main']['App']['GetResourceTimeline'](arg1);
}

export function GetSecurityInfo() {
  return window['go']['main']['App']['GetSecurityInfo']();
}

export function GetSecurityInfoWithGeo() {
  return window['go']['main']['App']['GetSecurityInfoWithGeo']();
}

export function GetSystemContext() {
  return window['go']['main']['App']['GetSystemContext']();
}

export function GetSystemStats() {
  return window['go']['main']['App']['GetSystemStats']();
}

export function IsAIConfigured() {
  return window['go']['main']['App']['IsAIConfigured']();
}

export function KillProcess(arg1) {
  return window['go']['main']['App']['KillProcess'](arg1);
}

export function MarkInsightAsRead(arg1) {
  return window['go']['main']['App']['MarkInsightAsRead'](arg1);
}

export function RemoveContainer(arg1) {
  return window['go']['main']['App']['RemoveContainer'](arg1);
}

export function RestartContainer(arg1) {
  return window['go']['main']['App']['RestartContainer'](arg1);
}

export function SendChatMessage(arg1, arg2) {
  return window['go']['main']['App']['SendChatMessage'](arg1, arg2);
}

export function SendChatMessageStreaming(arg1, arg2) {
  return window['go']['main']['App']['SendChatMessageStreaming'](arg1, arg2);
}

export function SetAIConfig(arg1) {
  return window['go']['main']['App']['SetAIConfig'](arg1);
}

export function SetAlertConfig(arg1) {
  return window['go']['main']['App']['SetAlertConfig'](arg1);
}

export function SetProcessPriority(arg1, arg2) {
  return window['go']['main']['App']['SetProcessPriority'](arg1, arg2);
}

export function StartContainer(arg1) {
  return window['go']['main']['App']['StartContainer'](arg1);
}

export function StopContainer(arg1) {
  return window['go']['main']['App']['StopContainer'](arg1);
}

export function UpdateChatSessionTitle(arg1, arg2) {
  return window['go']['main']['App']['UpdateChatSessionTitle'](arg1, arg2);
}
